# ~/.config/starship.toml
# Global format for Starship prompt
format = """\
$time \
$directory \
$git_branch \
$character"""

# Time module
[time]
disabled = false
time_format = "%H:%M"
style = "fg:#83C193"  # Changed to forestbones light color
format = "[  $time]($style)"

# Directory module
[directory]
style = "fg:#B7CDD8"  # Changed to forestbones medium color
format = "[ $path]($style)"

# Git branch module
[git_branch]
symbol = " "
style = "fg:#AFD6D6"  # Changed to forestbones accent color
format = "[$symbol$branch]($style)"

# Character module
[character]
success_symbol = "[➜ ](fg:#D69AB7)"  # Changed to forestbones success color
error_symbol = "[✗](bold #E67C7F)"    # Changed to forestbones error color
style = "fg:#B0CE7B"                  # Changed to forestbones medium color

